version: "3"

services:

  postgres:
    image: postgres:14-alpine
    volumes:
      - .data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    restart: always
    env_file:
      - .env

  web:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/flask-project/app
      - ./logs:/home/flask-project/logs
    ports:
      - "5000:5000"
    command: >
      bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done;
      flask db upgrade;
      gunicorn --bind 0.0.0.0:5000 -w 2 "app:create_app()"'
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - FLASK_APP=app:create_app()