"""followers m2m table

Revision ID: 510e02ba7bd1
Revises: 761e904db67a
Create Date: 2022-08-04 12:33:15.121661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510e02ba7bd1'
down_revision = '761e904db67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
