"""empty message

Revision ID: 761e904db67a
Revises: d61c24738863
Create Date: 2022-08-03 12:44:48.540794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761e904db67a'
down_revision = 'd61c24738863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
